/**
 * The bundled exercise photos as a static `require` map, which is how Metro bundles an image:
 * a path it can see at build time. `npm run catalog:images` writes it from the dataset, and a
 * jest test renders it again and fails when the committed file differs, so a dataset edit that
 * forgets to regenerate cannot ship.
 *
 * An exercise in `pendingPhotos.json` is left out: its files do not exist yet, and a `require`
 * of a missing file fails the whole bundle. Kept free of the app's modules, so `tsx` runs it.
 */
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

/** The generated file, from the repository root. */
export const CATALOG_IMAGES_OUTPUT = 'features/exercises/mappers/catalogImages.generated.ts';

const ROOT = resolve(__dirname, '..');
const FRAMES = { start: '0', end: '1', thumb: 'thumb' } as const;

interface DatasetImages {
  readonly id: string;
  readonly images: Readonly<Record<keyof typeof FRAMES, string>>;
}

/** What the map is generated from: the dataset's exercises and the ids still waiting for photos. */
export function readCatalogImageInputs(): { exercises: readonly DatasetImages[]; pending: readonly string[] } {
  const read = (file: string) => JSON.parse(readFileSync(resolve(ROOT, 'assets/catalog', file), 'utf8'));
  return { exercises: read('exercises.json').exercises, pending: read('pendingPhotos.json') };
}

/**
 * The slug of `exercise`, after checking its images follow the one layout the app resolves:
 * `images/<slug>/0.webp`, `1.webp` and `thumb.webp`, where the slug is the id without `ex:`.
 */
function slugOf(exercise: DatasetImages): string {
  const slug = exercise.id.replace(/^ex:/, '');
  for (const [frame, file] of Object.entries(FRAMES)) {
    const expected = `images/${slug}/${file}.webp`;
    const actual = exercise.images[frame as keyof typeof FRAMES];
    if (actual !== expected) throw new Error(`${exercise.id}: ${frame} is ${actual}, expected ${expected}`);
  }
  return slug;
}

/** The text of the generated file, one entry per exercise with photos, in dataset order. */
export function renderCatalogImages(exercises: readonly DatasetImages[], pending: readonly string[]): string {
  const waiting = new Set(pending);
  const entries = exercises
    .filter(exercise => !waiting.has(exercise.id))
    .map(exercise => {
      const slug = slugOf(exercise);
      const frames = Object.entries(FRAMES).map(
        ([frame, file]) => `    ${frame}: require('@/assets/catalog/images/${slug}/${file}.webp'),`,
      );
      return [`  '${slug}': {`, ...frames, '  },'].join('\n');
    });
  return [
    '/**',
    ' * Generated by `npm run catalog:images` from `assets/catalog/exercises.json`: do not edit by hand.',
    ' * Every bundled photo, by exercise slug, as the asset Metro bundled; an exercise waiting for its',
    ' * photos in `pendingPhotos.json` has no entry.',
    ' */',
    'export const CATALOG_IMAGES: Readonly<Record<string, { start: number; end: number; thumb: number }>> = {',
    ...entries,
    '};',
    '',
  ].join('\n');
}
